:game:
  :bye: "Morpheus: 'Follow me.'"  
:bg:
  :scene: Matrix
  :chars: "!#$%&\\\/()*+,-.01:;<=>?@[]^_oO{}|ª·¿•xX "
:fg:
  :scene: Slider
  :files: "examples/1.demo/*.txt"
:ui:
  :scene: UI
  :header: "Gema diamante"
