:game:
  :bye: "Morpheus: 'Follow me.'"  
:bg:
  :scene: Matrix
  # :chars: "!#$%&\()*+,-.0123456789:;<=>?@[]^_oO{}|ª·¿• "
  :chars: "!#$%&\\\/()*+,-.01:;<=>?@[]^_oO{}|ª·¿•xX "
:fg:
  :scene: Slider
  :files: "examples/yaml/*.txt"
:ui:
  :scene: UI
  :header: "Gema diamante"
