:game:
  :bye: "Morpheus: 'Follow me.'"  
:bg:
  :scene: Matrix
  :chars: "ª\\|@·#$~%&\/¿¸^*¨;•:·_-+'., ."
:fg:
  :scene: Slider
  :files: "examples/yaml/*.txt"
:ui:
  :scene: UI
  :header: "Gema diamante"
